git:
  autoStageResolvedConflicts: false
  autoFetch: false
  #branchLogCmd: git log --graph --first-parent --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  pagers:
    - pager: delta --dark --paging=never --line-numbers -s
    - pager: delta --dark --paging=never --line-numbers
os:
  copyToClipboardCmd: printf "\033]52;c;$(printf {{text}} | base64 -w 0)\a" > /dev/tty
gui:
  scrollHeight: 20
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - '#6f806f'
    selectedRangeBgColor:
      - '#6f806f'
customCommands:
  - key: 'U'
    command: 'git submodule update --init --recursive'
    context: 'files'
    description: 'Update submodules'
    output: log
  - key: 'u'
    command: 'git submodule update -- {{.SelectedFile.Name}}'
    context: 'files'
    description: 'Update submodule'
  - key: "<c-p>"
    context: "files"
    prompts:
      - type: "input"
        title: "Nazwa docelowej gałęzi w Gerrit (np. main, master):"
        key: "Branch"
    command: "git push origin HEAD:refs/for/{{.Form.Branch}}"
    description: "Push do Gerrit (refs/for/)"
    output: terminal
